--1. 학생이름과 주소지를 표시하시오. 단, 출력 헤더는 "학생 이름", "주소지"로 하고, 정렬은 이름으로 오름차순 표시

SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT
ORDER BY "학생 이름";

--2. 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서로 화면에 출력하시오.
SELECT STUDENT_NAME AS "학생 이름", STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3.주소지가 강원도나 경기도인 학생들 중 1900 년대 학번을 가진 학생들의 이름과 학번, 주소를 이름의 오름차순으로 화면에 출력하시오. 
SELECT STUDENT_NAME AS "학생이름", STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%') AND STUDENT_NO LIKE '9%'
ORDER BY 학생이름;

--4. 현재 법학과 교수 중 가장 나이가 ＠ 사람부터 이름을 확인 수 있는 SQL 문장, (법학과의 '학과코드'는 학과 테이블(TB_DEPARTMENT)을 조회)
SELECT STUDENT_NAME AS "학생이름", STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%') AND STUDENT_NO LIKE '9%'
ORDER BY 학생이름;

--5. 2004 년 2 학기에 'C3118100' 과목을 수강 학생들의 학점을 조회하려고 다. 
--학점이 높은 학생부터 표시하고, 학점이 같으면 학번이 낮은 학생부터 표시
SELECT STUDENT_NO, ROUND(POINT, 2)
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY POINT DESC, STUDENT_NO;

--6. 학생 번호, 학생 이름, 학과 이름을 학생 이름으로 오름차순 정렬하여 출력하는 SQL

SELECT STUDENT_NO,STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT,TB_DEPARTMENT
WHERE TB_DEPARTMENT.DEPARTMENT_NO = TB_STUDENT.DEPARTMENT_NO
ORDER BY STUDENT_NAME;

--7.과목 이름과 과목의 학과 이름을 출력하는 SQL 문장을 작성하시오.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS,TB_DEPARTMENT
WHERE TB_DEPARTMENT.DEPARTMENT_NO = TB_CLASS.DEPARTMENT_NO;

--8. 과목별 교수 이름을 찾으려고 다. 과목 이름과 교수 이름을 출력하는 SQL 문
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS,TB_CLASS_PROFESSOR,TB_PROFESSOR
WHERE TB_CLASS.CLASS_NO = TB_CLASS_PROFESSOR.CLASS_NO  AND TB_PROFESSOR.PROFESSOR_NO = TB_CLASS_PROFESSOR.PROFESSOR_NO;

--9. 8 번의 결과 중 ‘인문사회’ 계열에 속 과목의 교수 이름을 찾으려고 다. 이에 해당하는 과목 이름과 교수 이름을 출력하는 SQL 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS,TB_CLASS_PROFESSOR,TB_PROFESSOR,TB_DEPARTMENT
WHERE TB_CLASS.CLASS_NO = TB_CLASS_PROFESSOR.CLASS_NO  AND TB_PROFESSOR.PROFESSOR_NO = TB_CLASS_PROFESSOR.PROFESSOR_NO 
AND TB_PROFESSOR.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO AND CATEGORY='인문사회';

--10.‘음악학과’ 학생들의 평점을 구하려고 다. 음악학과 학생들의 "학번", "학생 이름",
--"전 평점"을 출력하는 SQL 문장을 작성하시오. (단, 평점은 소수점 1 자리까지만 반올림하여 표시다.)

SELECT TB_STUDENT.STUDENT_NO AS 학번, TB_STUDENT.STUDENT_NAME AS "학생 이름", ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_GRADE,TB_STUDENT,TB_DEPARTMENT
WHERE TB_DEPARTMENT.DEPARTMENT_NO = TB_STUDENT.DEPARTMENT_NO AND DEPARTMENT_NAME='음악학과' AND TB_STUDENT.STUDENT_NO = TB_GRADE.STUDENT_NO
GROUP BY TB_STUDENT.STUDENT_NO,TB_STUDENT.STUDENT_NAME
ORDER BY TB_STUDENT.STUDENT_NO;

--11. 학번이 A313047의 학과 이름, 학생 이름과 지도 교수 이름이 필요하다.

SELECT DEPARTMENT_NAME AS 학과이름, STUDENT_NAME AS 학생이름, PROFESSOR_NAME AS 지도교수이름 
FROM TB_STUDENT, TB_DEPARTMENT,TB_PROFESSOR
WHERE TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO AND TB_STUDENT.COACH_PROFESSOR_NO=TB_PROFESSOR.PROFESSOR_NO
AND TB_STUDENT.STUDENT_NO = 'A313047';

--12. 2007 년도에 '인간관계론' 과목을 수강한 학생을 찾아 학생이름과 수강학기를 표시하는 SQL
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT,TB_GRADE,TB_CLASS
WHERE TB_STUDENT.STUDENT_NO = TB_GRADE.STUDENT_NO AND TB_CLASS.CLASS_NO=TB_GRADE.CLASS_NO
AND TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

--13. 예체능 계열 과목 중 과목 담당교수를  명도 배정받지 못 과목을 찾아 그 과목이름과 학과 이름을 출력하는 SQL 문장을 작성하시오.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS LEFT OUTER JOIN TB_CLASS_PROFESSOR ON TB_CLASS_PROFESSOR.CLASS_NO = TB_CLASS.CLASS_NO
LEFT OUTER JOIN TB_DEPARTMENT ON TB_DEPARTMENT.DEPARTMENT_NO = TB_CLASS.DEPARTMENT_NO
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL ;





