--1. 대학교 학과명, 계열을 표시하시오. 헤더는 '학과명' '계열'으로 표시한다

SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열
FROM TB_DEPARTMENT;

--2. 학과의 정원을 출력
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

--3. "국어국문학과"에 다니는 여학생중 휴학중인 학생
SELECT STUDENT_NAME
FROM TB_DEPARTMENT, TB_STUDENT
WHERE TB_DEPARTMENT.DEPARTMENT_NAME IN ('국어국문학과') AND TB_STUDENT.ABSENCE_YN IN ('Y') AND STUDENT_SSN LIKE '%-2%' AND TB_DEPARTMENT.DEPARTMENT_NO = TB_STUDENT.DEPARTMENT_NO;

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

--5.입학정원이 20 명 이상 30 명 이하인 학과들의 학과 이름과 계열을 출력하시오.
SELECT DEPARTMENT_NAME , CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 

--6. 총장을 제외하고 모든 교수들이 소속 학과를 가지고 있다. 그럼 총장의 이름을 알아낼 수 있는 SQL 문장을 작성하시오.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL ;

--7.학과가 지정되어 있지 않은 학생이 있는지 확인
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8. 선수과목이 존재하는 과목들은 어떤 과목인지 과목번호를 조회해보시오.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9. 어떤 계열(CATEGORY)들이 있는지 조회해보시오.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10. 02학번 전주 거주자들의 모임을 휴학한 사람들 제외 재학중인 학생들의 학번, 이름, 주민번호를 출력하는 구문을 작성하시오.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN IN ('N') AND STUDENT_ADDRESS LIKE '%전주%' AND ENTRANCE_DATE LIKE '02%';
